// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAowz0b_SjWGBMtpEY9bZSUXfov0rSHbew',
    appId: '1:460536689477:web:07ca27ff428ecced46c42c',
    messagingSenderId: '460536689477',
    projectId: 'group-capstone-dde0d',
    authDomain: 'group-capstone-dde0d.firebaseapp.com',
    storageBucket: 'group-capstone-dde0d.appspot.com',
    measurementId: 'G-MH0P0SH1DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqOuIQ-cdITd7Xx5eBpHcmX9CplLLF2Do',
    appId: '1:460536689477:android:1b6e954411b0ba8746c42c',
    messagingSenderId: '460536689477',
    projectId: 'group-capstone-dde0d',
    storageBucket: 'group-capstone-dde0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQRDm6wBpPK_IBpqvtAJaP1erID8O5iI',
    appId: '1:460536689477:ios:dcb092b670f78d4346c42c',
    messagingSenderId: '460536689477',
    projectId: 'group-capstone-dde0d',
    storageBucket: 'group-capstone-dde0d.appspot.com',
    iosBundleId: 'com.example.code',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPQRDm6wBpPK_IBpqvtAJaP1erID8O5iI',
    appId: '1:460536689477:ios:b4558996ef18ebbf46c42c',
    messagingSenderId: '460536689477',
    projectId: 'group-capstone-dde0d',
    storageBucket: 'group-capstone-dde0d.appspot.com',
    iosBundleId: 'com.example.code.RunnerTests',
  );
}
